site_name: Deep Learning AI Course Notes
site_url: https://shashankshekhar.com/dlai-course-notes/
repo_url: https://github.com/sshkhr/dlai-course-notes
theme:
  name: material
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: red
      accent: deep orange
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: red
      accent: deep orange
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home: index.md
  - Notes:
    - LLMOps: notes/llmops.md
    - Building Generative AI Applications with Gradio: notes/building-generative-ai-applications-with-gradio.md
    - Chat GPT Prompt Engineering for Developers: notes/chat-gpt-prompt-engineering-for-developers.md
    - Pair Programming with a LLM: notes/pair-programming-with-a-llm.md
    - Prompt Engineering with Llama 2&3: notes/prompt-engineering-with-llama-2&3.md
    - Understanding and Applying Text Embeddings: notes/understanding-and-applying-text-embeddings.md

# Set the directory containing your documentation
docs_dir: docs

# Additional configurations
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sshkhr/dlai-course-notes
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sshkhr16
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sshkhr/
    