site_name: DeepLearning.AI Companion
site_url: https://shashankshekhar.com/dlai-companion
repo_name: sshkhr/dlai-companion
repo_url: https://github.com/sshkhr/dlai-companion
theme:
  name: material

  icon:
    logo: material/school
    tag:
      data-preprocessing: fontawesome/solid/database
      semantic-search: fontawesome/solid/magnifying-glass
      vector-emebddings: fontawesome/solid/bars
      mlops: fontawesome/solid/gears
      rag: fontawesome/solid/repeat
      course-notes: fontawesome/solid/book
      vision: fontawesome/solid/eye
      safeguards: fontawesome/solid/shield
      llm: fontawesome/solid/language
      prompt-engineering: fontawesome/solid/wrench
      llm4code: fontawesome/solid/keyboard
  
  favicon: assets/favicon_dark.png

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: red
      accent: deep orange
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: red
      accent: deep orange
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      
nav:
  - About: index.md 
  - Courses: catalog.md
  - Notes:
    - Preprocessing Unstructured Data for LLM Applications: notes/preprocessing-unstructured-data-for-llm-applications.md
  - Reviews:
    - Preprocessing Unstructured Data for LLM Applications: reviews/preprocessing-unstructured-data-for-llm-applications.md
  - Learning Paths:
    - How To - Build a Basic RAG: learning_paths/build-a-basic-rag.md
  - Tags: tags.md

# Set the directory containing your documentation
docs_dir: docs

# Additional configurations
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      base_path: docs/snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.escapeall
  - pymdownx.tilde


plugins:
  - search
  - tags:
      tags_file: tags.md
  - social
      cards_layout_options:
        background_color: red

extra:
  tags:
    Data Preprocessing: data-preprocessing
    Semantic Search: semantic-search
    Vector Embeddings: vector-embeddings
    MLOps: mlops
    RAG: rag
    Course Notes: course-notes

    
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sshkhr/dlai-course-notes
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sshkhr16
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sshkhr/

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css


copyright: Copyright &copy; 2024 Shashank Shekhar
    