site_name: DeepLearning.AI Coompanion
site_url: https://shashankshekhar.com/dlai-course-notes/
repo_url: https://github.com/sshkhr/dlai-course-notes
theme:
  name: material

  icon:
    logo: material/school-outlines

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: red
      accent: deep orange
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: red
      accent: deep orange
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  icon:
    tag:
      data-preprocessing: fontawesome/solid/database
      semantic-search: fontawesome/solid/magnifying-glass
      vector-emebddings: fontawesome/solid/bars
      mlops: fontawesome/solid/gears
      rag: fontawesome/solid/repeat
      course-notes: fontawesome/solid/book
      
nav:
  - About: index.md
  - Course Notes:
    - Preprocessing Unstructured Data for LLM Applications: notes/preprocessing-unstructured-data-for-llm-applications.md
    - LLMOps: notes/llmops.md
    - Building Generative AI Applications with Gradio: notes/building-generative-ai-applications-with-gradio.md
    - Chat GPT Prompt Engineering for Developers: notes/chat-gpt-prompt-engineering-for-developers.md
    - Pair Programming with a LLM: notes/pair-programming-with-a-llm.md
    - Prompt Engineering with Llama 2&3: notes/prompt-engineering-with-llama-2&3.md
    - Understanding and Applying Text Embeddings: notes/understanding-and-applying-text-embeddings.md
  - Learning Paths:
    - How To - Build a Basic RAG: learning_paths/build-a-basic-rag.md
  - Tags: tags.md

# Set the directory containing your documentation
docs_dir: docs

# Additional configurations
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
plugins:
  - search
  - tags:
      tags_file: tags.md
  - social


extra:
  tags:
    Data Preprocessing: data-preprocessing
    Semantic Search: semantic-search
    Vector Embeddings: vector-embeddings
    MLOps: mlops
    RAG: rag
    Course Notes: course-notes

    
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sshkhr/dlai-course-notes
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sshkhr16
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sshkhr/

copyright: Copyright &copy; 2024 Shashank Shekhar
    